name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  release:
    uses: biolab/orange-ci-cd/.github/workflows/release.yml@master
    with:
      pure-python: false
    secrets: inherit
